### ISSUE TITLE
User UX

### ISSUE THREAD

**Issue by ericdallo** [aidalgol/dockered-language-servers#7]
Hi, the idea of this project sounds great to me, but I think we can improve it somehow the user UX, I mean, if a user want to use a LS from this repo for they development, what are the steps? does user needs to download this repo? It'd be great if they just install a global `dockered-lsp` command where then it could be called like `dockered-lsp run clojure-lsp` or something like that.

I'm just trying to think in a better way where user wouldn't need to clone this repo and start pointing to the .sh files... WDYT?

**Comment by aidalgol** [comment]
I agree the UX could be improved.  Ideally, we would have the images build automatically and pushed to Docker Hub, users would then just pull the image they want, and then that just leaves the issue of the wrapper script.  I like your idea of a global command.  https://github.com/xendk/rid looks kind of like what we want, but a bit more generic.  I think we could achieve what we need for this project with a simple bash script with just one big switch statement.

**Comment by xendk** [comment]
Well, one advantage of rid is that you can symlink `bash-language-server` to `rid` somewhere in your path, and as `lsp-mode` looks for a command named `bash-language-server` It Just Works™. I'm planning to add a switch which will make `rid` create all the commands in a `.rid.yml` file automatically. 

Of course, we could also make a bin dir in this repo which contains all the language servers under their canonical name.

But it does bring up another issue. `rid` mounts in the directory of the `.rid.yml` file rather than `$HOME` for a reason. I have been meaning to add a warning to the rid readme, advising against putting a `.rid.yml` in your home dir but rather putting it one level deeper, like `~/dev` or what one prefers.

The problem with mounting in ones homedir is that it gives a container access to all you own, including sensitive directories like `.ssh` and `.gnupg`. In *theory* this means you could accidentally run a malicious image which would grab all your keys and send them off to the dark web.

It's a small risk, but it seems prudent to limit the damage a malicious image might inflict.

(and I better get that added to the readme)

**Comment by aidalgol** [comment]
> Well, one advantage of rid is that you can symlink `bash-language-server` to `rid` somewhere in your path, and as `lsp-mode` looks for a command named `bash-language-server` It Just Works™. I'm planning to add a switch which will make `rid` create all the commands in a `.rid.yml` file automatically.
> 
> Of course, we could also make a bin dir in this repo which contains all the language servers under their canonical name.

Those both sound like good options.  The bin dir in this repo as the easier option, and using `rid` as the more flexible option.

> But it does bring up another issue. `rid` mounts in the directory of the `.rid.yml` file rather than `$HOME` for a reason. I have been meaning to add a warning to the rid readme, advising against putting a `.rid.yml` in your home dir but rather putting it one level deeper, like `~/dev` or what one prefers.

That would make it difficult to use with at least elixir-ls, because it also uses the language's package manager, so I would want to expose `~/src` *and* `~/.mix`, which doesn't sound like it would be possible with the mechanism `rid` currently provides for specifying which directory to mount in the container.

**Comment by xendk** [comment]
> That would make it difficult to use with at least elixir-ls, because it also uses the language's package manager, so I would want to expose ~/src and ~/.mix, which doesn't sound like it would be possible with the mechanism rid currently provides for specifying which directory to mount in the container.

Not to worry, I got that covered, see the `platform` command in the [readme](https://github.com/xendk/rid/blob/main/README.md). You can specify additional mount points. Another option is the `cache` option. These are also extra directories mounted in, but rid manages them per command. Means they're empty on the first invocation, but will persist between invocations (they're stored in `.config/rid/<command>`). 

As you can see, rid doesn't impose any limits on specified mounts, I mount in my `.ssh` dir on platform, as it uses the `ssh` command and my key.

Though I'm still pondering whether I should reverse the logic and make *not* mounting the root folder (and the setting of user and current working directory) the default and require an command option for that behavior.

**Comment by aidalgol** [comment]
What do you both think of the changes in the `easier-wrapper-scripts` branch?  It combines the wrapper scripts into a single wrapper script that takes the language-server name/identifier as the first argument, or can be invoked via a symlink with the same name as the language-server's executable, making it entirely transparent to the client.

This is deliberately kept simple, so that there is something convenient provided by this repo, and for a more flexibility, users can instead use `rid`.

**Comment by xendk** [comment]
Think you should warn users about the `$HOME` mounting. Apart from that, looks good.

One more thing you might consider copying from rid: `--workdir $PWD`. I don't know how relevant it is for language servers, as long as they're working with full paths, it should just work.

**Comment by aidalgol** [comment]
I think I have plugged that last security risk properly now (instead of it just being a known limitation of the wrapper script), and I am going to merge it to `main`.  Feel free to reopen this ticket or open a new one if anyone has any further input.
